name: forexpulsepro
services:
- name: web
  source_dir: /
  github:
    repo: Samerabualsoud/ForexPulsePro
    branch: main
  run_command: python app_server.py
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 5000
  routes:
  - path: /
  envs:
  - key: PORT
    value: "5000"
  - key: PYTHONPATH
    value: "/app"
  - key: LD_LIBRARY_PATH
    value: "/usr/local/lib"
  - key: JWT_SECRET
    value: "your_secure_jwt_secret_change_in_production"
  - key: LOG_LEVEL
    value: "INFO"
