# Production secrets configuration
# SET THESE VALUES IN PRODUCTION ENVIRONMENT

[general]
# JWT Secret for authentication (CHANGE THIS IN PRODUCTION!)
JWT_SECRET = "forex_dashboard_secret_CHANGE_IN_PRODUCTION_2024"

# Database Configuration  
DATABASE_URL = "postgresql://username:password@host:port/database"

# API Keys
FINNHUB_API_KEY = "your_finnhub_key_here"
ALPHAVANTAGE_KEY = "your_alpha_vantage_key_here"

# WhatsApp Integration
# WhatsApp integration removed - no longer needed
# WHATSAPP_ACCESS_TOKEN = "removed"  
# WHATSAPP_PHONE_ID = "removed"

[security]
# Password hashing settings
PASSWORD_HASH_ROUNDS = 12
SESSION_TIMEOUT_HOURS = 24